stateDiagram-v2
%% Source: design-spec/state/system/connection-card-review.system.ts
[*] --> connectionCardReviewSystem_awaitingConnectionReview_sv36wr
state "awaitingConnectionReview" as connectionCardReviewSystem_awaitingConnectionReview_sv36wr
state "awaitingCardReview" as connectionCardReviewSystem_awaitingCardReview_lse2b1
state "closedConnectionArchived" as connectionCardReviewSystem_closedConnectionArchived_ppap3v
state "closedCardArchived" as connectionCardReviewSystem_closedCardArchived_ic5zkn
state "closedCardAccepted" as connectionCardReviewSystem_closedCardAccepted_b80xss
connectionCardReviewSystem_awaitingConnectionReview_sv36wr --> connectionCardReviewSystem_awaitingConnectionReview_sv36wr: confirmConnection
connectionCardReviewSystem_awaitingConnectionReview_sv36wr --> connectionCardReviewSystem_awaitingConnectionReview_sv36wr: archiveConnection
connectionCardReviewSystem_awaitingConnectionReview_sv36wr --> connectionCardReviewSystem_awaitingCardReview_lse2b1: ConnectionConfirmed
connectionCardReviewSystem_awaitingConnectionReview_sv36wr --> connectionCardReviewSystem_closedConnectionArchived_ppap3v: ConnectionArchived
connectionCardReviewSystem_awaitingCardReview_lse2b1 --> connectionCardReviewSystem_awaitingCardReview_lse2b1: acceptSuggestedCard
connectionCardReviewSystem_awaitingCardReview_lse2b1 --> connectionCardReviewSystem_awaitingCardReview_lse2b1: archiveCard
connectionCardReviewSystem_awaitingCardReview_lse2b1 --> connectionCardReviewSystem_closedCardAccepted_b80xss: CardAccepted
connectionCardReviewSystem_awaitingCardReview_lse2b1 --> connectionCardReviewSystem_closedCardArchived_ic5zkn: CardArchived
connectionCardReviewSystem_closedConnectionArchived_ppap3v --> [*]
connectionCardReviewSystem_closedCardArchived_ic5zkn --> [*]
connectionCardReviewSystem_closedCardAccepted_b80xss --> [*]
